name: Feature Request
description: Suggest an idea for this project
title: ":large_orange_diamond: "
labels: ["feature"]
assignees:
  - geriremenyi
body:
  - type: markdown
    id: intro
    attributes:
      value: |
        Please fill in the details to request a feature!
  - type: textarea
    id: what
    attributes:
      label: What would you add?
      description: Tell us, what do you want to add and how would you imagine it working!
      placeholder: Tell us, what do you want to add and how would you imagine it working!
    validations:
      required: true
  - type: textarea
    id: extra-context
    attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the feature you are requesting!

      Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/geriremenyi/oanda-v20-openapi/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
