openapi: 3.0.3
info:
  title: OANDA v20 API
  description: The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
  contact:
    name: OANDA API Support
    url: http://developer.oanda.com/rest-live-v20/introduction/
    email: api@oanda.com
  license:
    name: MIT
    url: https://github.com/geriremenyi/oanda-openapi/blob/main/LICENSE
  version: 3.0.25
paths: {}